apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f0hu0xbg3-nodejs
  janus-idp.io/tekton: f0hu0xbg3-nodejs
  backstage.io/kubernetes-id: f0hu0xbg3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f0hu0xbg3-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
