apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: f0hu0xbg3-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f0hu0xbg3-nodejs 
  name: f0hu0xbg3-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: f0hu0xbg3-nodejs
    weight: 100 
